/**
 * @file Event.h
 * @brief The event base class, its type/category enumerations and the dispatcher.
 * @ingroup group_events
 */

#pragma once

#include "ugpch.h"
#include "Uge/Core/Core.h"

namespace Uge
{

	//Events in Uge are currently blocking, meaning when an event occurs it
	//immediately gets dispatched and must be dealt with right then and there.
	//For the future, a better stragegy might be to buffer events in an event 
	//bus and process them during the "event" part of the update stage.

	/**
	 * @brief Identifies the concrete type of an Uge::Event at runtime.
	 * @ingroup group_events
	 *
	 * Each Event subclass reports its value through `GetEventType()`, generated by the
	 * #EVENT_CLASS_TYPE macro. Uge::EventDispatcher compares against it to decide whether
	 * a handler applies.
	 */
	enum class EventType
	{

		None = 0, ///< Unset / invalid.
		WindowClose, ///< The user closed the window. @see Uge::WindowCloseEvent
		WindowResize, ///< The window was resized. @see Uge::WindowResizeEvent
		WindowFocus, ///< The window gained focus.
		WindowLostFocus, ///< The window lost focus.
		WindowMoved, ///< The window was moved.
		AppTick, ///< Fixed-rate application tick. @see Uge::AppTickEvent
		AppUpdate, ///< Application update. @see Uge::AppUpdateEvent
		AppRender, ///< Application render. @see Uge::AppRenderEvent
		KeyPressed, ///< A key went down or repeated. @see Uge::KeyPressedEvent
		KeyReleased, ///< A key went up. @see Uge::KeyReleasedEvent
		KeyTyped, ///< A character was typed. @see Uge::KeyTypedEvent
		MouseButtonPressed, ///< A mouse button went down. @see Uge::MouseButtonPressedEvent
		MouseButtonReleased, ///< A mouse button went up. @see Uge::MouseButtonReleasedEvent
		MouseMoved, ///< The cursor moved. @see Uge::MouseMovedEvent
		MouseScrolled ///< The wheel was scrolled. @see Uge::MouseScrolledEvent

	};

	/**
	 * @brief Bit flags letting a layer filter whole families of events at once.
	 * @ingroup group_events
	 *
	 * An event may belong to several categories: a mouse click is both
	 * #EventCategoryMouse and #EventCategoryInput. Test membership with
	 * Uge::Event::IsInCategory rather than comparing the raw flags.
	 */
	enum EventCategory
	{

		None = 0, ///< No category.
		EventCategoryApplication	= BIT(0), ///< Window and application lifecycle events.
		EventCategoryInput			= BIT(1), ///< Any user input event.
		EventCategoryKeyboard		= BIT(2), ///< Keyboard events.
		EventCategoryMouse			= BIT(3), ///< Mouse movement and wheel events.
		EventCategoryMouseButton	= BIT(4) ///< Mouse button events.


	};

/**
 * @def EVENT_CLASS_TYPE
 * @brief Implements the type-identification members of an Uge::Event subclass.
 * @param type The unqualified Uge::EventType enumerator, e.g. `WindowClose`.
 * @ingroup group_events
 *
 * Expands to `GetStaticType()`, `GetEventType()` and `GetName()`. `GetStaticType()` is
 * what makes Uge::EventDispatcher::Dispatch able to match on the compile-time type.
 * Place it in the public section of every concrete event class.
 */
#define EVENT_CLASS_TYPE(type)	static EventType GetStaticType() { return EventType::##type; }\
								virtual EventType GetEventType() const override { return GetStaticType(); }\
								virtual const char* GetName() const override { return #type; }
/**
 * @def EVENT_CLASS_CATEGORY
 * @brief Implements `GetCategoryFlags()` for an Uge::Event subclass.
 * @param category One or more Uge::EventCategory flags combined with `|`.
 * @ingroup group_events
 */
#define EVENT_CLASS_CATEGORY(category) virtual int GetCategoryFlags() const override { return category; }


	/**
	 * @brief Base class for everything the window reports: input, resize, focus, close.
	 * @ingroup group_events
	 *
	 * Events are dispatched immediately and synchronously: the window raises one from
	 * inside Uge::Window::OnUpdate, Uge::Application::OnEvent offers it to each layer from
	 * top to bottom, and propagation stops as soon as a layer sets #m_handled.
	 *
	 * Subclasses are expected to use #EVENT_CLASS_TYPE and #EVENT_CLASS_CATEGORY rather
	 * than implementing the virtuals by hand.
	 *
	 * @code
	 * void EditorLayer::OnEvent(Event& e)
	 * {
	 *     EventDispatcher dispatcher(e);
	 *     dispatcher.Dispatch<KeyPressedEvent>(UG_BIND_EVENT_FN(EditorLayer::OnKeyPressed));
	 * }
	 * @endcode
	 *
	 * @note Dispatch is blocking by design. Buffering events on a queue and draining them
	 * during a dedicated phase of the frame would be a possible future change.
	 */
	class Event
	{
		friend class EventDispatcher;

	public:
		bool m_handled = false; ///< Set to `true` to stop propagation to lower layers.


		/**
		 * @brief Runtime type of this event.
		 * @return The event's Uge::EventType.
		 */
		virtual EventType GetEventType() const = 0;
		/**
		 * @brief Human-readable class name, for logging.
		 * @return A static string such as `"WindowResize"`.
		 */
		virtual const char* GetName() const = 0;
		/**
		 * @brief The Uge::EventCategory flags this event belongs to.
		 * @return A bitwise OR of category flags.
		 */
		virtual int GetCategoryFlags() const = 0;
		/**
		 * @brief Describes the event, including its payload.
		 * @return A string for logging; defaults to GetName().
		 */
		virtual std::string ToString() const { return GetName(); };

		/**
		 * @brief Tests whether this event belongs to a category.
		 * @param category Category to test for.
		 * @return `true` if the flag is set.
		 */
		inline bool IsInCategory(EventCategory category)
		{
			
			return GetCategoryFlags() & category;
		}

	};

	/**
	 * @brief Routes an event to a handler when its runtime type matches.
	 * @ingroup group_events
	 *
	 * Construct one around the event a layer received, then call Dispatch() once per event
	 * type of interest. Only the matching call runs its handler, so the usual pattern is a
	 * short list of dispatches with no branching.
	 *
	 * @see UG_BIND_EVENT_FN for binding member functions as handlers.
	 */
	class EventDispatcher
	{

		/**
		 * @brief Handler signature; return `true` to mark the event handled.
		 * @tparam T Concrete event type the handler accepts.
		 */
		template<typename T>
		using EventFn = std::function<bool(T&)>;

	public:
		/**
		 * @brief Wraps an event for dispatching.
		 * @param event Event to route; must outlive the dispatcher.
		 */
		EventDispatcher(Event& event)
			: m_event(event){ }

		/**
		 * @brief Invokes @p func if the wrapped event is of type `T`.
		 * @tparam T Concrete event type to match against.
		 * @param func Handler receiving the event downcast to `T&`.
		 * @return `true` if the types matched and the handler ran, `false` otherwise.
		 *
		 * The handler's return value is stored in Event::m_handled, so returning `true` stops
		 * the event from reaching lower layers.
		 *
		 * @warning The return value reports whether the handler *ran*, not whether it handled
		 * the event.
		 */
		template<typename T>
		bool Dispatch(EventFn<T> func)
		{

			if (m_event.GetEventType() == T::GetStaticType())
			{

				m_event.m_handled = func(*(T*)&m_event);
				return true;
			}
			return false;

		}
		
	private:
		Event& m_event;


	};

	/**
	 * @brief Streams an event's description, so events work with the logging macros.
	 * @param os Destination stream.
	 * @param e Event to write.
	 * @return @p os, for chaining.
	 * @ingroup group_events
	 */
	inline std::ostream& operator<<(std::ostream& os, const Event& e)
	{
		return os << e.ToString();
	}




}